#!/bin/bash

KERNEL=/mnt/vmvol0/tmp/vm/devuan-jessie/vmlinuz
ROOT=/var/chroot/devuan
INITRD=/mnt/vmvol0/tmp/vm/devuan-jessie/initrd.gz

qemu-system-x86_64 \
    -enable-kvm \
    -kernel $KERNEL \
    -initrd $INITRD \
    -fsdev local,id=root9p,path=$ROOT,security_model=mapped \
    -device virtio-9p-pci,fsdev=root9p,mount_tag=root9p \
    -append 'root=root9p rw rootfstype=9p rootflags=trans=virtio console=ttyS0'

#    -append 'root=root9p rw rootfstype=9p rootflags=trans=virtio console=ttyS0'
#    -initrd /vmroot/trusty/boot/initrd.img-3.13.0-24-generic \
#    -nographic \
