#!/bin/bash

IMGSTORE=/mnt/vmvol0

if [ ! "$2" ]; then
    echo "$0 <name> <size>" >&2
    exit
fi

die() {
    echo "$0: $*" >&2
    exit 1
}

name="$1"
size="$2"

echo "name: $name size=$size"

IMGPATH=$IMGSTORE/vm-images/$name

mkdir -p $(dirname "$IMGPATH")

btrfs subvolume create $IMGPATH || die "failed to create btrfs volume - vm name already used ?"
